<a href="https://colab.research.google.com/github/Anitha-Naresh/Python-DA-Assignment-1-Numpy-and-Pandas/blob/main/Python_DA_Assignment_1%E2%80%93Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# PYTHON DATA ANALYTICS ASSIGNMENT 1
# NUMPY AND PANDAS


In [18]:
# Import libraries
import numpy as np
import pandas as pd

In [ ]:
# NUMPY ARRAY OPERATIONS

In [3]:
# 1. Create a 1D NumPy Array
temperatures_w1 = np.array([
    22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9
])

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [4]:
# 2. Inspection and Properties
print("\nShape of temperatures_w1:")
print(temperatures_w1.shape)

print("\nData type of temperatures_w1:")
print(temperatures_w1.dtype)

print("\nNumber of elements:")
print(temperatures_w1.size)



Shape of temperatures_w1:
(7,)

Data type of temperatures_w1:
float64

Number of elements:
7


In [5]:
# 3. Array Operations

# Convert Celsius to Fahrenheit
temperatures_fahrenheit = (temperatures_w1 * 9/5) + 32

print("\nTemperatures in Fahrenheit:")
print(temperatures_fahrenheit)

# Maximum temperature
maximum_temperature = np.max(temperatures_w1)

print("\nMaximum temperature:")
print(maximum_temperature)

# Minimum temperature
minimum_temperature = np.min(temperatures_w1)

print("\nMinimum temperature:")
print(minimum_temperature)

# Mean temperature
mean_temperature = np.mean(temperatures_w1)

print("\nMean temperature:")
print(mean_temperature)


Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum temperature:
26.1

Minimum temperature:
20.8

Mean temperature:
23.542857142857144


In [6]:
# 4. Array Slicing and Indexing

# First three days
first_three_days = temperatures_w1[:3]

print("\nTemperatures for the first three days:")
print(first_three_days)

# Weekend - last two days
weekend_temperatures = temperatures_w1[-2:]

print("\nWeekend temperatures:")
print(weekend_temperatures)

# Middle three days
middle_three_days = temperatures_w1[2:5]

print("\nMiddle three days:")
print(middle_three_days)


Temperatures for the first three days:
[22.5 25.3 20.8]

Weekend temperatures:
[24.8 21.9]

Middle three days:
[20.8 23.4 26.1]


In [8]:
# CREATE 2D NUMPY ARRAY
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("\n========================================")
print("2D TEMPERATURE ARRAY")
print("========================================")

print("\nTemperatures:")
print(temperatures)


2D TEMPERATURE ARRAY

Temperatures:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [9]:
# 6. Inspect the 2D Array

print("\nShape of temperatures:")
print(temperatures.shape)

print("\nData type of temperatures:")
print(temperatures.dtype)

print("\nTotal number of elements:")
print(temperatures.size)


# Extract Week 1
week1 = temperatures[0]

print("\nWeek 1 temperatures:")
print(week1)

# Extract Week 2
week2 = temperatures[1]

print("\nWeek 2 temperatures:")
print(week2)

# Weekend temperatures for both weeks
weekend_both_weeks = temperatures[:, -2:]

print("\nWeekend temperatures for both weeks:")
print(weekend_both_weeks)



Shape of temperatures:
(2, 7)

Data type of temperatures:
float64

Total number of elements:
14

Week 1 temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend temperatures for both weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [10]:
#PANDAS SERIES
# 1. Creating Pandas Series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("\n========================================")
print("PANDAS SERIES")
print("========================================")

print("\nMarks Series:")
print(marks)


PANDAS SERIES

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [11]:
# 2. Indexing and Slicing

# Integer index position to access 1st rank
first_rank_mark = marks.iloc[0]

print("\nMark of 1st rank student:")
print(first_rank_mark)


# Using loc to retrieve top 3 ranks
top_three_ranks = marks.loc[['Rank1', 'Rank2', 'Rank3']]

print("\nMarks of top 3 rank students:")
print(top_three_ranks)


# Using iloc to retrieve 3rd-ranked student
third_rank_mark = marks.iloc[2]

print("\nMark of 3rd-ranked student:")
print(third_rank_mark)


# Boolean mask for marks greater than 90
marks_greater_than_90 = marks[marks > 90]

print("\nRanks where marks are greater than 90:")
print(marks_greater_than_90)


Mark of 1st rank student:
95

Marks of top 3 rank students:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of 3rd-ranked student:
89

Ranks where marks are greater than 90:
Rank1    95
Rank2    92
dtype: int64


In [12]:
# 3. Manipulating Series

# Modify Rank1 mark to 100
marks.loc['Rank1'] = 100

print("\nMarks after changing Rank1 to 100:")
print(marks)


# Remove Rank5
marks = marks.drop('Rank5')

print("\nMarks after removing Rank5:")
print(marks)


# Calculate CGPA
cgpa = marks / 10

print("\nCGPA:")
print(cgpa)


Marks after changing Rank1 to 100:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

Marks after removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [14]:
#PANDAS DATAFRAME
# 1. Creating Pandas DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics',
        'Clothing',
        'Electronics',
        'Furniture',
        'Clothing',
        'Electronics',
        'Furniture',
        'Clothing',
        'Furniture',
        'Electronics'
    ],

    'Region': [
        'North',
        'South',
        'North',
        'East',
        'West',
        'North',
        'East',
        'West',
        'South',
        'North'
    ],

    'Amount': [
        200,
        150,
        300,
        450,
        200,
        250,
        300,
        180,
        350,
        400
    ]
})

print("\n========================================")
print("TRANSACTIONS DATAFRAME")
print("========================================")

print("\nTransactions DataFrame:")
print(transactions)




TRANSACTIONS DATAFRAME

Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [15]:
#2. DATA EXPLORATION
# Display first 5 rows
print("\nFirst 5 rows:")
print(transactions.head())


# Display last 5 rows
print("\nLast 5 rows:")
print(transactions.tail())


# Display shape
print("\nShape of DataFrame:")
print(transactions.shape)


# Display column names
print("\nColumn names:")
print(transactions.columns)


# Display data types
print("\nData types:")
print(transactions.dtypes)


# Display basic information
print("\nBasic information:")
transactions.info()


# Display ProductCategory and Amount columns
print("\nProductCategory and Amount:")
print(transactions[['ProductCategory', 'Amount']])


# Retrieve last 3 columns
print("\nLast 3 columns:")
print(transactions.iloc[:, -3:])


# Filter Region = North and Amount > 200
north_amount_greater_200 = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print("\nNorth region with Amount greater than 200:")
print(north_amount_greater_200)


# Value counts for ProductCategory
product_category_counts = transactions['ProductCategory'].value_counts()

print("\nProduct Category value counts:")
print(product_category_counts)


# Unique values in Region
unique_regions = transactions['Region'].unique()

print("\nUnique regions:")
print(unique_regions)


# Group by Region and calculate mean Amount
mean_amount_by_region = transactions.groupby('Region')['Amount'].mean()

print("\nMean Amount by Region:")
print(mean_amount_by_region)





First 5 rows:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape of DataFrame:
(10, 4)

Column names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

Data types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column        

In [16]:
# 3. DATAFRAME MANIPULATION
# Modify Amount for TransactionID 102 to 165
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print("\nAfter changing TransactionID 102 Amount to 165:")
print(transactions)


# Add Discount column = 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter adding Discount column:")
print(transactions)


# Remove TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
].reset_index(drop=True)

print("\nAfter removing TransactionID 109:")
print(transactions)


# Delete Discount column
transactions = transactions.drop(columns=['Discount'])

print("\nAfter deleting Discount column:")
print(transactions)



After changing TransactionID 102 Amount to 165:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After adding Discount column:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     

In [17]:
# FINAL DATAFRAME

print("\n========================================")
print("FINAL TRANSACTIONS DATAFRAME")
print("========================================")

print(transactions)


FINAL TRANSACTIONS DATAFRAME
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            110     Electronics  North     400
